#基础的配置文件
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 20
    accept-count: 500
    max-connections: 200
spring:
  datasource:
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pgiot.cvnwqmyht6r9.rds.cn-north-1.amazonaws.com.cn:5432/iot-device11
    username: pgiot
    password: ENC(iEZ95DHshzBHng0ADOOYXQwBv6pWdgJY)
  banner:
    location: banner/dev.txt
  redis:
    host: localhost
    password:
    port: 6379
    database: 0
    timeout: 2000
    ssl: true
    jedis:
      pool:
        max-active: 200
        max-idle: 30
        min-idle: 20
        max-wait: -1


---
spring:
  profiles: qa
  banner:
    location: banner/qa.txt

---
spring:
  profiles: prod
  banner:
    location: banner/prod.txt

---
aws:
  clientarn: arn:aws-cn:iot:cn-north-1:784024438107